-- M3: Signal engine tables for persisting generated signals
-- Apply to Supabase via SQL Editor or CLI

-- Signal records generated by the signal engine
CREATE TABLE IF NOT EXISTS signals (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    asset_class VARCHAR(10) NOT NULL,
    timeframe VARCHAR(10) NOT NULL,
    bucket CHAR(1) NOT NULL CHECK (bucket IN ('A', 'B')),
    bar_timestamp TIMESTAMPTZ NOT NULL,

    -- Regime
    regime VARCHAR(12) NOT NULL CHECK (regime IN ('bull', 'bear', 'transition')),
    regime_distance_pct DOUBLE PRECISION,
    regime_strongly_aligned BOOLEAN NOT NULL DEFAULT FALSE,

    -- Direction & conditions
    signal_direction VARCHAR(5) NOT NULL CHECK (signal_direction IN ('long', 'short')),
    conditions_met SMALLINT NOT NULL CHECK (conditions_met BETWEEN 0 AND 3),

    -- Individual conditions
    trend_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    structure_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    structure_multi_method BOOLEAN NOT NULL DEFAULT FALSE,
    momentum_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    volume_spike BOOLEAN NOT NULL DEFAULT FALSE,

    -- Scoring
    signal_score SMALLINT NOT NULL CHECK (signal_score BETWEEN 0 AND 6),
    signal_tradeable BOOLEAN NOT NULL DEFAULT FALSE,

    -- Exit levels
    entry_price DOUBLE PRECISION NOT NULL,
    exit_stop DOUBLE PRECISION,
    exit_target DOUBLE PRECISION,
    exit_trail_be DOUBLE PRECISION,
    exit_risk DOUBLE PRECISION,
    exit_reward DOUBLE PRECISION,
    exit_rr_ratio DOUBLE PRECISION,

    -- Metadata
    config_hash VARCHAR(64),  -- SHA-256 of signals.yaml for reproducibility
    created_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(symbol, timeframe, bar_timestamp, signal_direction)
);

CREATE INDEX IF NOT EXISTS idx_signals_symbol_tf
    ON signals(symbol, timeframe, bar_timestamp);

CREATE INDEX IF NOT EXISTS idx_signals_tradeable
    ON signals(signal_tradeable, signal_score DESC)
    WHERE signal_tradeable = TRUE;

CREATE INDEX IF NOT EXISTS idx_signals_regime
    ON signals(regime, signal_direction);

CREATE INDEX IF NOT EXISTS idx_signals_bucket
    ON signals(bucket);
